//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterSvcRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    public partial class User : object
    {
        
        private string MailField;
        
        private string MobilePhoneNoField;
        
        private string OfficeCodeField;
        
        private string OfficeDescField;
        
        private string OldUserIdField;
        
        private string OrgDescTHField;
        
        private int OrgIDField;
        
        private string PreNameField;
        
        private string UpdateByField;
        
        private System.DateTime UpdateDateField;
        
        private string UserIDField;
        
        private string codeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhoneNo
        {
            get
            {
                return this.MobilePhoneNoField;
            }
            set
            {
                this.MobilePhoneNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeCode
        {
            get
            {
                return this.OfficeCodeField;
            }
            set
            {
                this.OfficeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeDesc
        {
            get
            {
                return this.OfficeDescField;
            }
            set
            {
                this.OfficeDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldUserId
        {
            get
            {
                return this.OldUserIdField;
            }
            set
            {
                this.OldUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgDescTH
        {
            get
            {
                return this.OrgDescTHField;
            }
            set
            {
                this.OrgDescTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrgID
        {
            get
            {
                return this.OrgIDField;
            }
            set
            {
                this.OrgIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreName
        {
            get
            {
                return this.PreNameField;
            }
            set
            {
                this.PreNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateBy
        {
            get
            {
                return this.UpdateByField;
            }
            set
            {
                this.UpdateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDate
        {
            get
            {
                return this.UpdateDateField;
            }
            set
            {
                this.UpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    public partial class ProcessResult : object
    {
        
        private string ErrorMessageField;
        
        private bool SuccessedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successed
        {
            get
            {
                return this.SuccessedField;
            }
            set
            {
                this.SuccessedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSearch", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    public partial class UserSearch : object
    {
        
        private string CodeField;
        
        private string FirstNameField;
        
        private bool IncludeSubOrgField;
        
        private string LastNameField;
        
        private string OfficeField;
        
        private string OrgDescField;
        
        private int OrgIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeSubOrg
        {
            get
            {
                return this.IncludeSubOrgField;
            }
            set
            {
                this.IncludeSubOrgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Office
        {
            get
            {
                return this.OfficeField;
            }
            set
            {
                this.OfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgDesc
        {
            get
            {
                return this.OrgDescField;
            }
            set
            {
                this.OrgDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrgID
        {
            get
            {
                return this.OrgIDField;
            }
            set
            {
                this.OrgIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    public partial class Organization : object
    {
        
        private string CodeField;
        
        private string DepartCodeField;
        
        private string DepartDescENField;
        
        private string DepartDescTHField;
        
        private string DescENField;
        
        private string DescTHField;
        
        private string DivCodeField;
        
        private string DivDescENField;
        
        private string DivDescTHField;
        
        private int IDField;
        
        private int LevelField;
        
        private string LineCodeField;
        
        private string LineDescENField;
        
        private string LineDescTHField;
        
        private string UpdateByField;
        
        private System.DateTime UpdateDateField;
        
        private string UplineCodeField;
        
        private string UplineDescENField;
        
        private string UplineDescTHField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartCode
        {
            get
            {
                return this.DepartCodeField;
            }
            set
            {
                this.DepartCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartDescEN
        {
            get
            {
                return this.DepartDescENField;
            }
            set
            {
                this.DepartDescENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartDescTH
        {
            get
            {
                return this.DepartDescTHField;
            }
            set
            {
                this.DepartDescTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEN
        {
            get
            {
                return this.DescENField;
            }
            set
            {
                this.DescENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescTH
        {
            get
            {
                return this.DescTHField;
            }
            set
            {
                this.DescTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivCode
        {
            get
            {
                return this.DivCodeField;
            }
            set
            {
                this.DivCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivDescEN
        {
            get
            {
                return this.DivDescENField;
            }
            set
            {
                this.DivDescENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivDescTH
        {
            get
            {
                return this.DivDescTHField;
            }
            set
            {
                this.DivDescTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineCode
        {
            get
            {
                return this.LineCodeField;
            }
            set
            {
                this.LineCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineDescEN
        {
            get
            {
                return this.LineDescENField;
            }
            set
            {
                this.LineDescENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineDescTH
        {
            get
            {
                return this.LineDescTHField;
            }
            set
            {
                this.LineDescTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateBy
        {
            get
            {
                return this.UpdateByField;
            }
            set
            {
                this.UpdateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDate
        {
            get
            {
                return this.UpdateDateField;
            }
            set
            {
                this.UpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UplineCode
        {
            get
            {
                return this.UplineCodeField;
            }
            set
            {
                this.UplineCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UplineDescEN
        {
            get
            {
                return this.UplineDescENField;
            }
            set
            {
                this.UplineDescENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UplineDescTH
        {
            get
            {
                return this.UplineDescTHField;
            }
            set
            {
                this.UplineDescTHField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Office", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    public partial class Office : object
    {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private string OldCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldCode
        {
            get
            {
                return this.OldCodeField;
            }
            set
            {
                this.OldCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POSITION", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    public partial class POSITION : object
    {
        
        private string DESCRIPTIONField;
        
        private int ZTB_POSITION_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION
        {
            get
            {
                return this.DESCRIPTIONField;
            }
            set
            {
                this.DESCRIPTIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZTB_POSITION_ID
        {
            get
            {
                return this.ZTB_POSITION_IDField;
            }
            set
            {
                this.ZTB_POSITION_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JOB_LEVEL", Namespace="http://schemas.datacontract.org/2004/07/CenterProvider")]
    public partial class JOB_LEVEL : object
    {
        
        private string DESCRIPTIONField;
        
        private int ZTB_JOB_LEVEL_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION
        {
            get
            {
                return this.DESCRIPTIONField;
            }
            set
            {
                this.DESCRIPTIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZTB_JOB_LEVEL_ID
        {
            get
            {
                return this.ZTB_JOB_LEVEL_IDField;
            }
            set
            {
                this.ZTB_JOB_LEVEL_IDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CenterSvcRef.ICenterService")]
    public interface ICenterService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getUser", ReplyAction="http://tempuri.org/ICenterService/getUserResponse")]
        CenterSvcRef.getUserResponse getUser(CenterSvcRef.getUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getUser", ReplyAction="http://tempuri.org/ICenterService/getUserResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.getUserResponse> getUserAsync(CenterSvcRef.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getUserCollection", ReplyAction="http://tempuri.org/ICenterService/getUserCollectionResponse")]
        CenterSvcRef.getUserCollectionResponse getUserCollection(CenterSvcRef.getUserCollectionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getUserCollection", ReplyAction="http://tempuri.org/ICenterService/getUserCollectionResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.getUserCollectionResponse> getUserCollectionAsync(CenterSvcRef.getUserCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetUserByIds", ReplyAction="http://tempuri.org/ICenterService/GetUserByIdsResponse")]
        CenterSvcRef.GetUserByIdsResponse GetUserByIds(CenterSvcRef.GetUserByIdsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetUserByIds", ReplyAction="http://tempuri.org/ICenterService/GetUserByIdsResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetUserByIdsResponse> GetUserByIdsAsync(CenterSvcRef.GetUserByIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationCollection", ReplyAction="http://tempuri.org/ICenterService/getOrganizationCollectionResponse")]
        CenterSvcRef.getOrganizationCollectionResponse getOrganizationCollection(CenterSvcRef.getOrganizationCollectionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationCollection", ReplyAction="http://tempuri.org/ICenterService/getOrganizationCollectionResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.getOrganizationCollectionResponse> getOrganizationCollectionAsync(CenterSvcRef.getOrganizationCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationByCode", ReplyAction="http://tempuri.org/ICenterService/getOrganizationByCodeResponse")]
        CenterSvcRef.getOrganizationByCodeResponse getOrganizationByCode(CenterSvcRef.getOrganizationByCodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationByCode", ReplyAction="http://tempuri.org/ICenterService/getOrganizationByCodeResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.getOrganizationByCodeResponse> getOrganizationByCodeAsync(CenterSvcRef.getOrganizationByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationById", ReplyAction="http://tempuri.org/ICenterService/getOrganizationByIdResponse")]
        CenterSvcRef.getOrganizationByIdResponse getOrganizationById(CenterSvcRef.getOrganizationByIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationById", ReplyAction="http://tempuri.org/ICenterService/getOrganizationByIdResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.getOrganizationByIdResponse> getOrganizationByIdAsync(CenterSvcRef.getOrganizationByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOffice", ReplyAction="http://tempuri.org/ICenterService/GetOfficeResponse")]
        CenterSvcRef.GetOfficeResponse GetOffice(CenterSvcRef.GetOfficeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOffice", ReplyAction="http://tempuri.org/ICenterService/GetOfficeResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetOfficeResponse> GetOfficeAsync(CenterSvcRef.GetOfficeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByIsoRegion", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByIsoRegionResponse")]
        CenterSvcRef.GetOfficeByIsoRegionResponse GetOfficeByIsoRegion(CenterSvcRef.GetOfficeByIsoRegionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByIsoRegion", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByIsoRegionResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetOfficeByIsoRegionResponse> GetOfficeByIsoRegionAsync(CenterSvcRef.GetOfficeByIsoRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByCode", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByCodeResponse")]
        CenterSvcRef.Office GetOfficeByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByCode", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByCodeResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.Office> GetOfficeByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOrganization", ReplyAction="http://tempuri.org/ICenterService/GetOrganizationResponse")]
        CenterSvcRef.GetOrganizationResponse GetOrganization(CenterSvcRef.GetOrganizationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOrganization", ReplyAction="http://tempuri.org/ICenterService/GetOrganizationResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetOrganizationResponse> GetOrganizationAsync(CenterSvcRef.GetOrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByCodeArray", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByCodeArrayResponse")]
        CenterSvcRef.GetOfficeByCodeArrayResponse GetOfficeByCodeArray(CenterSvcRef.GetOfficeByCodeArrayRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetOfficeByCodeArray", ReplyAction="http://tempuri.org/ICenterService/GetOfficeByCodeArrayResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetOfficeByCodeArrayResponse> GetOfficeByCodeArrayAsync(CenterSvcRef.GetOfficeByCodeArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetUserBySearchKey", ReplyAction="http://tempuri.org/ICenterService/GetUserBySearchKeyResponse")]
        CenterSvcRef.GetUserBySearchKeyResponse GetUserBySearchKey(CenterSvcRef.GetUserBySearchKeyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetUserBySearchKey", ReplyAction="http://tempuri.org/ICenterService/GetUserBySearchKeyResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetUserBySearchKeyResponse> GetUserBySearchKeyAsync(CenterSvcRef.GetUserBySearchKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetAllUser", ReplyAction="http://tempuri.org/ICenterService/GetAllUserResponse")]
        CenterSvcRef.GetAllUserResponse GetAllUser(CenterSvcRef.GetAllUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetAllUser", ReplyAction="http://tempuri.org/ICenterService/GetAllUserResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetAllUserResponse> GetAllUserAsync(CenterSvcRef.GetAllUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetPosition", ReplyAction="http://tempuri.org/ICenterService/GetPositionResponse")]
        CenterSvcRef.GetPositionResponse GetPosition(CenterSvcRef.GetPositionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetPosition", ReplyAction="http://tempuri.org/ICenterService/GetPositionResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetPositionResponse> GetPositionAsync(CenterSvcRef.GetPositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getJobLevel", ReplyAction="http://tempuri.org/ICenterService/getJobLevelResponse")]
        CenterSvcRef.getJobLevelResponse getJobLevel(CenterSvcRef.getJobLevelRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getJobLevel", ReplyAction="http://tempuri.org/ICenterService/getJobLevelResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.getJobLevelResponse> getJobLevelAsync(CenterSvcRef.getJobLevelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationBySearch", ReplyAction="http://tempuri.org/ICenterService/getOrganizationBySearchResponse")]
        CenterSvcRef.getOrganizationBySearchResponse getOrganizationBySearch(CenterSvcRef.getOrganizationBySearchRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOrganizationBySearch", ReplyAction="http://tempuri.org/ICenterService/getOrganizationBySearchResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.getOrganizationBySearchResponse> getOrganizationBySearchAsync(CenterSvcRef.getOrganizationBySearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOfficeBySearch", ReplyAction="http://tempuri.org/ICenterService/getOfficeBySearchResponse")]
        CenterSvcRef.getOfficeBySearchResponse getOfficeBySearch(CenterSvcRef.getOfficeBySearchRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/getOfficeBySearch", ReplyAction="http://tempuri.org/ICenterService/getOfficeBySearchResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.getOfficeBySearchResponse> getOfficeBySearchAsync(CenterSvcRef.getOfficeBySearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetTerminatedUser", ReplyAction="http://tempuri.org/ICenterService/GetTerminatedUserResponse")]
        CenterSvcRef.GetTerminatedUserResponse GetTerminatedUser(CenterSvcRef.GetTerminatedUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetTerminatedUser", ReplyAction="http://tempuri.org/ICenterService/GetTerminatedUserResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetTerminatedUserResponse> GetTerminatedUserAsync(CenterSvcRef.GetTerminatedUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetProcessedTerminatedUserId", ReplyAction="http://tempuri.org/ICenterService/GetProcessedTerminatedUserIdResponse")]
        CenterSvcRef.GetProcessedTerminatedUserIdResponse GetProcessedTerminatedUserId(CenterSvcRef.GetProcessedTerminatedUserIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetProcessedTerminatedUserId", ReplyAction="http://tempuri.org/ICenterService/GetProcessedTerminatedUserIdResponse")]
        System.Threading.Tasks.Task<CenterSvcRef.GetProcessedTerminatedUserIdResponse> GetProcessedTerminatedUserIdAsync(CenterSvcRef.GetProcessedTerminatedUserIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string code;
        
        public getUserRequest()
        {
        }
        
        public getUserRequest(string code)
        {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.User getUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult processResult;
        
        public getUserResponse()
        {
        }
        
        public getUserResponse(CenterSvcRef.User getUserResult, CenterSvcRef.ProcessResult processResult)
        {
            this.getUserResult = getUserResult;
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserCollection", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUserCollectionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.UserSearch search;
        
        public getUserCollectionRequest()
        {
        }
        
        public getUserCollectionRequest(CenterSvcRef.UserSearch search)
        {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserCollectionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUserCollectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.User[] getUserCollectionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult processResult;
        
        public getUserCollectionResponse()
        {
        }
        
        public getUserCollectionResponse(CenterSvcRef.User[] getUserCollectionResult, CenterSvcRef.ProcessResult processResult)
        {
            this.getUserCollectionResult = getUserCollectionResult;
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserByIds", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserByIdsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] userIds;
        
        public GetUserByIdsRequest()
        {
        }
        
        public GetUserByIdsRequest(string[] userIds)
        {
            this.userIds = userIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserByIdsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserByIdsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ITUtility.ProcessResult GetUserByIdsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.User[] returnObjects;
        
        public GetUserByIdsResponse()
        {
        }
        
        public GetUserByIdsResponse(ITUtility.ProcessResult GetUserByIdsResult, CenterSvcRef.User[] returnObjects)
        {
            this.GetUserByIdsResult = GetUserByIdsResult;
            this.returnObjects = returnObjects;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationCollection", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrganizationCollectionRequest
    {
        
        public getOrganizationCollectionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationCollectionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrganizationCollectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Organization[] getOrganizationCollectionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult processResult;
        
        public getOrganizationCollectionResponse()
        {
        }
        
        public getOrganizationCollectionResponse(CenterSvcRef.Organization[] getOrganizationCollectionResult, CenterSvcRef.ProcessResult processResult)
        {
            this.getOrganizationCollectionResult = getOrganizationCollectionResult;
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationByCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrganizationByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string code;
        
        public getOrganizationByCodeRequest()
        {
        }
        
        public getOrganizationByCodeRequest(string code)
        {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationByCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrganizationByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Organization getOrganizationByCodeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult processResult;
        
        public getOrganizationByCodeResponse()
        {
        }
        
        public getOrganizationByCodeResponse(CenterSvcRef.Organization getOrganizationByCodeResult, CenterSvcRef.ProcessResult processResult)
        {
            this.getOrganizationByCodeResult = getOrganizationByCodeResult;
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrganizationByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long orgID;
        
        public getOrganizationByIdRequest()
        {
        }
        
        public getOrganizationByIdRequest(long orgID)
        {
            this.orgID = orgID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrganizationByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Organization getOrganizationByIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult processResult;
        
        public getOrganizationByIdResponse()
        {
        }
        
        public getOrganizationByIdResponse(CenterSvcRef.Organization getOrganizationByIdResult, CenterSvcRef.ProcessResult processResult)
        {
            this.getOrganizationByIdResult = getOrganizationByIdResult;
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOffice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfficeRequest
    {
        
        public GetOfficeRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfficeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfficeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Office[] GetOfficeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult pr;
        
        public GetOfficeResponse()
        {
        }
        
        public GetOfficeResponse(CenterSvcRef.Office[] GetOfficeResult, CenterSvcRef.ProcessResult pr)
        {
            this.GetOfficeResult = GetOfficeResult;
            this.pr = pr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfficeByIsoRegion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfficeByIsoRegionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string iso_flg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string app_region;
        
        public GetOfficeByIsoRegionRequest()
        {
        }
        
        public GetOfficeByIsoRegionRequest(string iso_flg, string app_region)
        {
            this.iso_flg = iso_flg;
            this.app_region = app_region;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfficeByIsoRegionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfficeByIsoRegionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Office[] GetOfficeByIsoRegionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult processResult;
        
        public GetOfficeByIsoRegionResponse()
        {
        }
        
        public GetOfficeByIsoRegionResponse(CenterSvcRef.Office[] GetOfficeByIsoRegionResult, CenterSvcRef.ProcessResult processResult)
        {
            this.GetOfficeByIsoRegionResult = GetOfficeByIsoRegionResult;
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrganization", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrganizationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long[] orgId;
        
        public GetOrganizationRequest()
        {
        }
        
        public GetOrganizationRequest(long[] orgId)
        {
            this.orgId = orgId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrganizationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrganizationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Organization[] GetOrganizationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult processResult;
        
        public GetOrganizationResponse()
        {
        }
        
        public GetOrganizationResponse(CenterSvcRef.Organization[] GetOrganizationResult, CenterSvcRef.ProcessResult processResult)
        {
            this.GetOrganizationResult = GetOrganizationResult;
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfficeByCodeArray", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfficeByCodeArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] code;
        
        public GetOfficeByCodeArrayRequest()
        {
        }
        
        public GetOfficeByCodeArrayRequest(string[] code)
        {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfficeByCodeArrayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfficeByCodeArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Office[] GetOfficeByCodeArrayResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public CenterSvcRef.ProcessResult processResult;
        
        public GetOfficeByCodeArrayResponse()
        {
        }
        
        public GetOfficeByCodeArrayResponse(CenterSvcRef.Office[] GetOfficeByCodeArrayResult, CenterSvcRef.ProcessResult processResult)
        {
            this.GetOfficeByCodeArrayResult = GetOfficeByCodeArrayResult;
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserBySearchKey", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserBySearchKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Organization org;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string search;
        
        public GetUserBySearchKeyRequest()
        {
        }
        
        public GetUserBySearchKeyRequest(CenterSvcRef.Organization org, string search)
        {
            this.org = org;
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserBySearchKeyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserBySearchKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.User[] GetUserBySearchKeyResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ITUtility.ProcessResult result;
        
        public GetUserBySearchKeyResponse()
        {
        }
        
        public GetUserBySearchKeyResponse(CenterSvcRef.User[] GetUserBySearchKeyResult, ITUtility.ProcessResult result)
        {
            this.GetUserBySearchKeyResult = GetUserBySearchKeyResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllUserRequest
    {
        
        public GetAllUserRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.User[] GetAllUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ITUtility.ProcessResult result;
        
        public GetAllUserResponse()
        {
        }
        
        public GetAllUserResponse(CenterSvcRef.User[] GetAllUserResult, ITUtility.ProcessResult result)
        {
            this.GetAllUserResult = GetAllUserResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPosition", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPositionRequest
    {
        
        public GetPositionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPositionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPositionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.POSITION[] GetPositionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ITUtility.ProcessResult pr;
        
        public GetPositionResponse()
        {
        }
        
        public GetPositionResponse(CenterSvcRef.POSITION[] GetPositionResult, ITUtility.ProcessResult pr)
        {
            this.GetPositionResult = GetPositionResult;
            this.pr = pr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJobLevel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getJobLevelRequest
    {
        
        public getJobLevelRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJobLevelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getJobLevelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.JOB_LEVEL[] getJobLevelResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ITUtility.ProcessResult pr;
        
        public getJobLevelResponse()
        {
        }
        
        public getJobLevelResponse(CenterSvcRef.JOB_LEVEL[] getJobLevelResult, ITUtility.ProcessResult pr)
        {
            this.getJobLevelResult = getJobLevelResult;
            this.pr = pr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationBySearch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrganizationBySearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string searchKey;
        
        public getOrganizationBySearchRequest()
        {
        }
        
        public getOrganizationBySearchRequest(string searchKey)
        {
            this.searchKey = searchKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationBySearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrganizationBySearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Organization[] getOrganizationBySearchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ITUtility.ProcessResult pr;
        
        public getOrganizationBySearchResponse()
        {
        }
        
        public getOrganizationBySearchResponse(CenterSvcRef.Organization[] getOrganizationBySearchResult, ITUtility.ProcessResult pr)
        {
            this.getOrganizationBySearchResult = getOrganizationBySearchResult;
            this.pr = pr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOfficeBySearch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOfficeBySearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string searchKey;
        
        public getOfficeBySearchRequest()
        {
        }
        
        public getOfficeBySearchRequest(string searchKey)
        {
            this.searchKey = searchKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOfficeBySearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOfficeBySearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.Office[] getOfficeBySearchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ITUtility.ProcessResult pr;
        
        public getOfficeBySearchResponse()
        {
        }
        
        public getOfficeBySearchResponse(CenterSvcRef.Office[] getOfficeBySearchResult, ITUtility.ProcessResult pr)
        {
            this.getOfficeBySearchResult = getOfficeBySearchResult;
            this.pr = pr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTerminatedUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTerminatedUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime refDate;
        
        public GetTerminatedUserRequest()
        {
        }
        
        public GetTerminatedUserRequest(System.DateTime refDate)
        {
            this.refDate = refDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTerminatedUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTerminatedUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CenterSvcRef.User[] GetTerminatedUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ITUtility.ProcessResult pr;
        
        public GetTerminatedUserResponse()
        {
        }
        
        public GetTerminatedUserResponse(CenterSvcRef.User[] GetTerminatedUserResult, ITUtility.ProcessResult pr)
        {
            this.GetTerminatedUserResult = GetTerminatedUserResult;
            this.pr = pr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProcessedTerminatedUserId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProcessedTerminatedUserIdRequest
    {
        
        public GetProcessedTerminatedUserIdRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProcessedTerminatedUserIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProcessedTerminatedUserIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] GetProcessedTerminatedUserIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ITUtility.ProcessResult pr;
        
        public GetProcessedTerminatedUserIdResponse()
        {
        }
        
        public GetProcessedTerminatedUserIdResponse(string[] GetProcessedTerminatedUserIdResult, ITUtility.ProcessResult pr)
        {
            this.GetProcessedTerminatedUserIdResult = GetProcessedTerminatedUserIdResult;
            this.pr = pr;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICenterServiceChannel : CenterSvcRef.ICenterService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CenterServiceClient : System.ServiceModel.ClientBase<CenterSvcRef.ICenterService>, CenterSvcRef.ICenterService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CenterServiceClient() : 
                base(CenterServiceClient.GetDefaultBinding(), CenterServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICenterService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CenterServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CenterServiceClient.GetBindingForEndpoint(endpointConfiguration), CenterServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CenterServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CenterServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CenterServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CenterServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CenterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.getUserResponse CenterSvcRef.ICenterService.getUser(CenterSvcRef.getUserRequest request)
        {
            return base.Channel.getUser(request);
        }
        
        public CenterSvcRef.User getUser(string code, out CenterSvcRef.ProcessResult processResult)
        {
            CenterSvcRef.getUserRequest inValue = new CenterSvcRef.getUserRequest();
            inValue.code = code;
            CenterSvcRef.getUserResponse retVal = ((CenterSvcRef.ICenterService)(this)).getUser(inValue);
            processResult = retVal.processResult;
            return retVal.getUserResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.getUserResponse> getUserAsync(CenterSvcRef.getUserRequest request)
        {
            return base.Channel.getUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.getUserCollectionResponse CenterSvcRef.ICenterService.getUserCollection(CenterSvcRef.getUserCollectionRequest request)
        {
            return base.Channel.getUserCollection(request);
        }
        
        public CenterSvcRef.User[] getUserCollection(CenterSvcRef.UserSearch search, out CenterSvcRef.ProcessResult processResult)
        {
            CenterSvcRef.getUserCollectionRequest inValue = new CenterSvcRef.getUserCollectionRequest();
            inValue.search = search;
            CenterSvcRef.getUserCollectionResponse retVal = ((CenterSvcRef.ICenterService)(this)).getUserCollection(inValue);
            processResult = retVal.processResult;
            return retVal.getUserCollectionResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.getUserCollectionResponse> getUserCollectionAsync(CenterSvcRef.getUserCollectionRequest request)
        {
            return base.Channel.getUserCollectionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetUserByIdsResponse CenterSvcRef.ICenterService.GetUserByIds(CenterSvcRef.GetUserByIdsRequest request)
        {
            return base.Channel.GetUserByIds(request);
        }
        
        public ITUtility.ProcessResult GetUserByIds(string[] userIds, out CenterSvcRef.User[] returnObjects)
        {
            CenterSvcRef.GetUserByIdsRequest inValue = new CenterSvcRef.GetUserByIdsRequest();
            inValue.userIds = userIds;
            CenterSvcRef.GetUserByIdsResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetUserByIds(inValue);
            returnObjects = retVal.returnObjects;
            return retVal.GetUserByIdsResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetUserByIdsResponse> GetUserByIdsAsync(CenterSvcRef.GetUserByIdsRequest request)
        {
            return base.Channel.GetUserByIdsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.getOrganizationCollectionResponse CenterSvcRef.ICenterService.getOrganizationCollection(CenterSvcRef.getOrganizationCollectionRequest request)
        {
            return base.Channel.getOrganizationCollection(request);
        }
        
        public CenterSvcRef.Organization[] getOrganizationCollection(out CenterSvcRef.ProcessResult processResult)
        {
            CenterSvcRef.getOrganizationCollectionRequest inValue = new CenterSvcRef.getOrganizationCollectionRequest();
            CenterSvcRef.getOrganizationCollectionResponse retVal = ((CenterSvcRef.ICenterService)(this)).getOrganizationCollection(inValue);
            processResult = retVal.processResult;
            return retVal.getOrganizationCollectionResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.getOrganizationCollectionResponse> getOrganizationCollectionAsync(CenterSvcRef.getOrganizationCollectionRequest request)
        {
            return base.Channel.getOrganizationCollectionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.getOrganizationByCodeResponse CenterSvcRef.ICenterService.getOrganizationByCode(CenterSvcRef.getOrganizationByCodeRequest request)
        {
            return base.Channel.getOrganizationByCode(request);
        }
        
        public CenterSvcRef.Organization getOrganizationByCode(string code, out CenterSvcRef.ProcessResult processResult)
        {
            CenterSvcRef.getOrganizationByCodeRequest inValue = new CenterSvcRef.getOrganizationByCodeRequest();
            inValue.code = code;
            CenterSvcRef.getOrganizationByCodeResponse retVal = ((CenterSvcRef.ICenterService)(this)).getOrganizationByCode(inValue);
            processResult = retVal.processResult;
            return retVal.getOrganizationByCodeResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.getOrganizationByCodeResponse> getOrganizationByCodeAsync(CenterSvcRef.getOrganizationByCodeRequest request)
        {
            return base.Channel.getOrganizationByCodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.getOrganizationByIdResponse CenterSvcRef.ICenterService.getOrganizationById(CenterSvcRef.getOrganizationByIdRequest request)
        {
            return base.Channel.getOrganizationById(request);
        }
        
        public CenterSvcRef.Organization getOrganizationById(long orgID, out CenterSvcRef.ProcessResult processResult)
        {
            CenterSvcRef.getOrganizationByIdRequest inValue = new CenterSvcRef.getOrganizationByIdRequest();
            inValue.orgID = orgID;
            CenterSvcRef.getOrganizationByIdResponse retVal = ((CenterSvcRef.ICenterService)(this)).getOrganizationById(inValue);
            processResult = retVal.processResult;
            return retVal.getOrganizationByIdResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.getOrganizationByIdResponse> getOrganizationByIdAsync(CenterSvcRef.getOrganizationByIdRequest request)
        {
            return base.Channel.getOrganizationByIdAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetOfficeResponse CenterSvcRef.ICenterService.GetOffice(CenterSvcRef.GetOfficeRequest request)
        {
            return base.Channel.GetOffice(request);
        }
        
        public CenterSvcRef.Office[] GetOffice(out CenterSvcRef.ProcessResult pr)
        {
            CenterSvcRef.GetOfficeRequest inValue = new CenterSvcRef.GetOfficeRequest();
            CenterSvcRef.GetOfficeResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetOffice(inValue);
            pr = retVal.pr;
            return retVal.GetOfficeResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetOfficeResponse> GetOfficeAsync(CenterSvcRef.GetOfficeRequest request)
        {
            return base.Channel.GetOfficeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetOfficeByIsoRegionResponse CenterSvcRef.ICenterService.GetOfficeByIsoRegion(CenterSvcRef.GetOfficeByIsoRegionRequest request)
        {
            return base.Channel.GetOfficeByIsoRegion(request);
        }
        
        public CenterSvcRef.Office[] GetOfficeByIsoRegion(string iso_flg, string app_region, out CenterSvcRef.ProcessResult processResult)
        {
            CenterSvcRef.GetOfficeByIsoRegionRequest inValue = new CenterSvcRef.GetOfficeByIsoRegionRequest();
            inValue.iso_flg = iso_flg;
            inValue.app_region = app_region;
            CenterSvcRef.GetOfficeByIsoRegionResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetOfficeByIsoRegion(inValue);
            processResult = retVal.processResult;
            return retVal.GetOfficeByIsoRegionResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetOfficeByIsoRegionResponse> GetOfficeByIsoRegionAsync(CenterSvcRef.GetOfficeByIsoRegionRequest request)
        {
            return base.Channel.GetOfficeByIsoRegionAsync(request);
        }
        
        public CenterSvcRef.Office GetOfficeByCode(string code)
        {
            return base.Channel.GetOfficeByCode(code);
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.Office> GetOfficeByCodeAsync(string code)
        {
            return base.Channel.GetOfficeByCodeAsync(code);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetOrganizationResponse CenterSvcRef.ICenterService.GetOrganization(CenterSvcRef.GetOrganizationRequest request)
        {
            return base.Channel.GetOrganization(request);
        }
        
        public CenterSvcRef.Organization[] GetOrganization(long[] orgId, out CenterSvcRef.ProcessResult processResult)
        {
            CenterSvcRef.GetOrganizationRequest inValue = new CenterSvcRef.GetOrganizationRequest();
            inValue.orgId = orgId;
            CenterSvcRef.GetOrganizationResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetOrganization(inValue);
            processResult = retVal.processResult;
            return retVal.GetOrganizationResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetOrganizationResponse> GetOrganizationAsync(CenterSvcRef.GetOrganizationRequest request)
        {
            return base.Channel.GetOrganizationAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetOfficeByCodeArrayResponse CenterSvcRef.ICenterService.GetOfficeByCodeArray(CenterSvcRef.GetOfficeByCodeArrayRequest request)
        {
            return base.Channel.GetOfficeByCodeArray(request);
        }
        
        public CenterSvcRef.Office[] GetOfficeByCodeArray(string[] code, out CenterSvcRef.ProcessResult processResult)
        {
            CenterSvcRef.GetOfficeByCodeArrayRequest inValue = new CenterSvcRef.GetOfficeByCodeArrayRequest();
            inValue.code = code;
            CenterSvcRef.GetOfficeByCodeArrayResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetOfficeByCodeArray(inValue);
            processResult = retVal.processResult;
            return retVal.GetOfficeByCodeArrayResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetOfficeByCodeArrayResponse> GetOfficeByCodeArrayAsync(CenterSvcRef.GetOfficeByCodeArrayRequest request)
        {
            return base.Channel.GetOfficeByCodeArrayAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetUserBySearchKeyResponse CenterSvcRef.ICenterService.GetUserBySearchKey(CenterSvcRef.GetUserBySearchKeyRequest request)
        {
            return base.Channel.GetUserBySearchKey(request);
        }
        
        public CenterSvcRef.User[] GetUserBySearchKey(CenterSvcRef.Organization org, string search, out ITUtility.ProcessResult result)
        {
            CenterSvcRef.GetUserBySearchKeyRequest inValue = new CenterSvcRef.GetUserBySearchKeyRequest();
            inValue.org = org;
            inValue.search = search;
            CenterSvcRef.GetUserBySearchKeyResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetUserBySearchKey(inValue);
            result = retVal.result;
            return retVal.GetUserBySearchKeyResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetUserBySearchKeyResponse> GetUserBySearchKeyAsync(CenterSvcRef.GetUserBySearchKeyRequest request)
        {
            return base.Channel.GetUserBySearchKeyAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetAllUserResponse CenterSvcRef.ICenterService.GetAllUser(CenterSvcRef.GetAllUserRequest request)
        {
            return base.Channel.GetAllUser(request);
        }
        
        public CenterSvcRef.User[] GetAllUser(out ITUtility.ProcessResult result)
        {
            CenterSvcRef.GetAllUserRequest inValue = new CenterSvcRef.GetAllUserRequest();
            CenterSvcRef.GetAllUserResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetAllUser(inValue);
            result = retVal.result;
            return retVal.GetAllUserResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetAllUserResponse> GetAllUserAsync(CenterSvcRef.GetAllUserRequest request)
        {
            return base.Channel.GetAllUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetPositionResponse CenterSvcRef.ICenterService.GetPosition(CenterSvcRef.GetPositionRequest request)
        {
            return base.Channel.GetPosition(request);
        }
        
        public CenterSvcRef.POSITION[] GetPosition(out ITUtility.ProcessResult pr)
        {
            CenterSvcRef.GetPositionRequest inValue = new CenterSvcRef.GetPositionRequest();
            CenterSvcRef.GetPositionResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetPosition(inValue);
            pr = retVal.pr;
            return retVal.GetPositionResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetPositionResponse> GetPositionAsync(CenterSvcRef.GetPositionRequest request)
        {
            return base.Channel.GetPositionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.getJobLevelResponse CenterSvcRef.ICenterService.getJobLevel(CenterSvcRef.getJobLevelRequest request)
        {
            return base.Channel.getJobLevel(request);
        }
        
        public CenterSvcRef.JOB_LEVEL[] getJobLevel(out ITUtility.ProcessResult pr)
        {
            CenterSvcRef.getJobLevelRequest inValue = new CenterSvcRef.getJobLevelRequest();
            CenterSvcRef.getJobLevelResponse retVal = ((CenterSvcRef.ICenterService)(this)).getJobLevel(inValue);
            pr = retVal.pr;
            return retVal.getJobLevelResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.getJobLevelResponse> getJobLevelAsync(CenterSvcRef.getJobLevelRequest request)
        {
            return base.Channel.getJobLevelAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.getOrganizationBySearchResponse CenterSvcRef.ICenterService.getOrganizationBySearch(CenterSvcRef.getOrganizationBySearchRequest request)
        {
            return base.Channel.getOrganizationBySearch(request);
        }
        
        public CenterSvcRef.Organization[] getOrganizationBySearch(string searchKey, out ITUtility.ProcessResult pr)
        {
            CenterSvcRef.getOrganizationBySearchRequest inValue = new CenterSvcRef.getOrganizationBySearchRequest();
            inValue.searchKey = searchKey;
            CenterSvcRef.getOrganizationBySearchResponse retVal = ((CenterSvcRef.ICenterService)(this)).getOrganizationBySearch(inValue);
            pr = retVal.pr;
            return retVal.getOrganizationBySearchResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.getOrganizationBySearchResponse> getOrganizationBySearchAsync(CenterSvcRef.getOrganizationBySearchRequest request)
        {
            return base.Channel.getOrganizationBySearchAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.getOfficeBySearchResponse CenterSvcRef.ICenterService.getOfficeBySearch(CenterSvcRef.getOfficeBySearchRequest request)
        {
            return base.Channel.getOfficeBySearch(request);
        }
        
        public CenterSvcRef.Office[] getOfficeBySearch(string searchKey, out ITUtility.ProcessResult pr)
        {
            CenterSvcRef.getOfficeBySearchRequest inValue = new CenterSvcRef.getOfficeBySearchRequest();
            inValue.searchKey = searchKey;
            CenterSvcRef.getOfficeBySearchResponse retVal = ((CenterSvcRef.ICenterService)(this)).getOfficeBySearch(inValue);
            pr = retVal.pr;
            return retVal.getOfficeBySearchResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.getOfficeBySearchResponse> getOfficeBySearchAsync(CenterSvcRef.getOfficeBySearchRequest request)
        {
            return base.Channel.getOfficeBySearchAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetTerminatedUserResponse CenterSvcRef.ICenterService.GetTerminatedUser(CenterSvcRef.GetTerminatedUserRequest request)
        {
            return base.Channel.GetTerminatedUser(request);
        }
        
        public CenterSvcRef.User[] GetTerminatedUser(System.DateTime refDate, out ITUtility.ProcessResult pr)
        {
            CenterSvcRef.GetTerminatedUserRequest inValue = new CenterSvcRef.GetTerminatedUserRequest();
            inValue.refDate = refDate;
            CenterSvcRef.GetTerminatedUserResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetTerminatedUser(inValue);
            pr = retVal.pr;
            return retVal.GetTerminatedUserResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetTerminatedUserResponse> GetTerminatedUserAsync(CenterSvcRef.GetTerminatedUserRequest request)
        {
            return base.Channel.GetTerminatedUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CenterSvcRef.GetProcessedTerminatedUserIdResponse CenterSvcRef.ICenterService.GetProcessedTerminatedUserId(CenterSvcRef.GetProcessedTerminatedUserIdRequest request)
        {
            return base.Channel.GetProcessedTerminatedUserId(request);
        }
        
        public string[] GetProcessedTerminatedUserId(out ITUtility.ProcessResult pr)
        {
            CenterSvcRef.GetProcessedTerminatedUserIdRequest inValue = new CenterSvcRef.GetProcessedTerminatedUserIdRequest();
            CenterSvcRef.GetProcessedTerminatedUserIdResponse retVal = ((CenterSvcRef.ICenterService)(this)).GetProcessedTerminatedUserId(inValue);
            pr = retVal.pr;
            return retVal.GetProcessedTerminatedUserIdResult;
        }
        
        public System.Threading.Tasks.Task<CenterSvcRef.GetProcessedTerminatedUserIdResponse> GetProcessedTerminatedUserIdAsync(CenterSvcRef.GetProcessedTerminatedUserIdRequest request)
        {
            return base.Channel.GetProcessedTerminatedUserIdAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICenterService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICenterService))
            {
                return new System.ServiceModel.EndpointAddress("http://intranetuat.bla.co.th:88/CenterWcfSvc/CenterWcf.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CenterServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICenterService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CenterServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICenterService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICenterService,
        }
    }
}
